modules:
  tcl:
    hash_length: 7
    naming_scheme: '{name}/{version}-{compiler.name}-{compiler.version}'
    all:
      conflict:
        - '{name}'
      environment:
        set: 
          '{name}_ROOT': '{prefix}'
