#!/bin/sh

export BUILD_MODE=${1:-DEBUG}
export EXTRA_BUILD_FLAGS=""

ARGS=(

  -D CMAKE_BUILD_TYPE:STRING="$BUILD_MODE"
  -D CMAKE_CXX_FLAGS:STRING="$EXTRA_BUILD_FLAGS"
  -D DART_TESTING_TIMEOUT:STRING=30

  -D Teuchos_ENABLE_LONG_LONG_INT:BOOL=ON
  -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
    -D Tpetra_INST_COMPLEX_FLOAT=OFF
    -D Tpetra_INST_COMPLEX_DOUBLE=OFF
    -D Tpetra_INST_INT_FLOAT=OFF
    -D Tpetra_INST_INT_LONG=ON
    -D Tpetra_INST_DOUBLE=ON
    -D Tpetra_INST_INT_LONG_LONG=ON
    #-D Tpetra_INST_INT_LONGLONG=ON

  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF

  -D Trilinos_ENABLE_Amesos:BOOL=ON
  -D Trilinos_ENABLE_Amesos2:BOOL=ON
    -D Amesos2_ENABLE_KLU2:BOOL=ON
    -D Amesos2_ENABLE_Basker:BOOL=ON
  -D Trilinos_ENABLE_Belos:BOOL=ON
  -D Trilinos_ENABLE_Epetra:BOOL=ON
  -D Trilinos_ENABLE_EpetraExt:BOOL=ON
  -D Trilinos_ENABLE_Galeri:BOOL=ON
  -D Trilinos_ENABLE_Ifpack:BOOL=ON

  -D Trilinos_ENABLE_Ifpack2:BOOL=ON
    -D Ifpack2_ENABLE_Experimental:BOOL=ON
    -D Ifpack2_ENABLE_TESTS:STRING=OFF

  -D Trilinos_ENABLE_Intrepid2:BOOL=ON

  -D Trilinos_ENABLE_MueLu:BOOL=ON
#    -D MueLu_ENABLE_BROKEN_TESTS:BOOL=ON
#    -D MueLu_ENABLE_Experimental:BOOL=ON
#    -D Xpetra_ENABLE_Experimental=ON
    -D MueLu_ENABLE_TESTS:STRING=ON
#    -D MueLu_ENABLE_EXAMPLES:STRING=ON
#    -D MueLu_ENABLE_Tutorial:BOOL=OFF

  -D Trilinos_ENABLE_Teuchos:BOOL=ON
    -D Teuchos_ENABLE_STACKTRACE:BOOL=OFF

  -D Trilinos_ENABLE_Tpetra:BOOL=ON

  -D Trilinos_ENABLE_Xpetra:BOOL=ON
    -D Xpetra_ENABLE_TESTS:STRING=OFF
    -D Xpetra_ENABLE_EXAMPLES:STRING=OFF

  -D Trilinos_ENABLE_Zoltan:BOOL=ON
  -D Trilinos_ENABLE_Zoltan2:BOOL=ON
    -D Zoltan2_ENABLE_Experimental:BOOL=ON

  -D TPL_ENABLE_SuperLU:BOOL=ON
  -D TPL_ENABLE_BLAS:BOOL=ON
  -D TPL_ENABLE_MPI:BOOL=ON
  -D TPL_ENABLE_Pthread:BOOL=OFF

  -D BUILD_SHARED_LIBS:BOOL=ON
  -D CMAKE_INSTALL_PREFIX:PATH="${PWD}"
  -D CMAKE_AR="/usr/bin/ar"
  -GNinja -DTrilinos_ENABLE_Fortran:BOOL=OFF

  -D Trilinos_GENERATE_REPO_VERSION_FILE:BOOL=ON
  -D Trilinos_ENABLE_SHADOW_WARNINGS:BOOL=ON
  -D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING=""
  -D Trilinos_ENABLE_TESTS:BOOL=OFF
  -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF

  -D BLAS_LIBRARY_DIRS:PATH="${BLAS_LIBRARY_DIRS}"
  -D BLAS_LIBRARY_DIRS:PATH="${BLAS_LIBRARY_DIRS}"
  -D LAPACK_LIBRARY_DIRS:PATH="${LAPACK_LIBRARY_DIRS}"
  -D LAPACK_LIBRARY_NAMES:STRING="${LAPACK_LIBRARY_NAMES}"

  -D SuperLU_LIBRARY_DIRS:PATH="${SEMS_SUPERLU_LIBRARY_PATH}"
  -D SuperLU_INCLUDE_DIRS:PATH="${SEMS_SUPERLU_INCLUDE_PATH}"

  -D METIS_LIBRARY_DIRS:PATH="${PARMETIS_LIBRARY_DIRS}"
  -D METIS_INCLUDE_DIRS:PATH="${PARMETIS_INCLUDE_DIRS}"
  -D ParMETIS_LIBRARY_DIRS:PATH="${PARMETIS_LIBRARY_DIRS}"
  -D ParMETIS_INCLUDE_DIRS:PATH="${PARMETIS_INCLUDE_DIRS}"

)

cmake  "${ARGS[@]}" $EXTRA_ARGS ${TRILINOS_HOME}
